### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by jadurani** [UPRI-NOAH/noah-frontend#1]
- [x] NOAH Logo Top Left
- [x] NOAH Text after logo
- [x] Create Text "Know the disaster. Be prepared"
- [x] Create sub-text. (See MVP)
- [x] Create Button "Assess My Area"
- [x] Create Assess My Area route to PRA Page 1 of 5
- [x] Create Slider/Preview
- [x] Add icon for Flood, Landslide and Storm Surge
- [x] Create Feature Quote Right
- [x] Create Feature Quote Left
- [x] Create Footer for Endcov, Blog, Contact Us, Copyright, and other related link
