### ISSUE TITLE
[UI] Feature/Playground Side Panel

### ISSUE THREAD

**Issue by jadurani** [UPRI-NOAH/noah-frontend#37]
- [x] Show hide side panel
- [x] Shown details form Figma mockup
- [x] Search component
- [x] 3D Terrain button
- [x] Flood Hazard component
- [x] Landslide Component
- [x] Storm Surge Component
- [x] Critical Facilities Component
