### ISSUE TITLE
[UI] Feature/Noah-Playground(MVP2): 3D Terrain

### ISSUE THREAD

**Issue by jadurani** [UPRI-NOAH/noah-frontend#44]
### To Do's
- [x] Show 3D Terrain Label
- [x] Collapsible icon
- [x] Checkbox for 3D Terrain
- [x] Exaggeration button from 0 to 10
