### ISSUE TITLE
[UI] Feature/Noah-Playground(MVP2): Change Basemap

### ISSUE THREAD

**Issue by jadurani** [UPRI-NOAH/noah-frontend#46]
### To Do's
- [ ] Show Satellite basemaps
- [ ] Show Mapbox basemaps
- [ ] Can switch to  selected basemaps
