### ISSUE TITLE
[UI] Feature/Landing Page: Add Autocomplete in Search

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#47]
# To Do's
- [x] Add text "Know Your Hazards"
- [x] Add subtext (see figma prototype)
- [x] Add input for Search with "Where do you live" text

#Screenshot
![image](https://user-images.githubusercontent.com/76890692/122754232-f7a35980-d2c5-11eb-85ed-b13cb4b96570.png)
