### ISSUE TITLE
[EPIC] Feature/Playground MVP1

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#53]
- [x] Search Location component
- [x] Zoom to search location
- [x] Toggle layers for Flood Component
- [x] Toggle layers for Landslide Component
- [x] Toggle layers for Storm Surge Component
- [x] Default location for Leyte Province
- [x] Show all layers for Critical Facilities
- [x] Legend for Critical Facilities
- [x] Legend for Flood
- [x] Legend for Storm Surge
- [x] Legend for Landslide
