### ISSUE TITLE
[EPIC] Personalized Risk Assessment MVP

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#54]
# Story

As a user, I should be informed of the risks due to natural hazards in my area and be informed of what I can do about it

## Step 1 - Location

- [x] Ask for the user's location
- [x] Inform the user of the risks that they will see as they go along in the story (inform them outright that they'll see flood maps, landslide maps, and storm surge maps)
- [x] Show the map and the user's pinned location

## Step 2 - Show flood risk level

- [x] Evaluate the user's risk level based on the their location
- [x] Show the hazard map in the area

## Step 3 - Show landslide risk level

- [x] Evaluate the user's risk level based on the their location
- [x] Show the hazard map in the area

## Step 4 - Show storm surge risk level 

- [x] Evaluate the user's risk level based on the their location
- [x] Show the hazard map in the area

## Step 5 - Show the critical facilities near the user's area

- Schools, Hospitals, Police Stations, Fire Stations
