### ISSUE TITLE
[Epic] Feature/Noah-Playground(MVP2): Critical Facilities Functionalities

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#66]
### To Do's
- [x] Toggle layers for Schools
- [x] Toggle layers for Hospital
- [x] Toggle layers for Fire Station
- [x] Toggle layers for Police Station
- [x] Change Opacity for Schools
- [x] Change Opacity for Hospitals
- [x] Change Opacity for Fire Station
- [x] Change Opacity for Police Station
