### ISSUE TITLE
[Epic] Feature/Noah-Playground(MVP2): Storm Surge Hazard Functionalities

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#68]
### To Do's
- [x] Show/Hide layers for Storm Surge Hazards
- [x] Toggle layers and show to Map for Storm Surge Advisory 1
- [x] Toggle layers and show to Map for Storm Surge Advisory 2
- [x] Toggle layers and show to Map for Storm Surge Advisory 3
- [x] Toggle layers and show to Map for Storm Surge Advisory 4
- [x] Can change Opacity from 0 to 100 for Storm Surge Advisory 1
- [x] Can change Opacity from 0 to 100 for Storm Surge Advisory 2
- [x] Can change Opacity from 0 to 100 for Storm Surge Advisory 3
- [x] Can change Opacity from 0 to 100 for Storm Surge Advisory 4
- [x] Can choose Color for Storm Surge Advisory 1 and change color layer in Map
- [x] Can choose Color for Storm Surge Advisory 2 and change color layer in Map
- [x] Can choose Color for Storm Surge Advisory 3 and change color layer in Map
- [x] Can choose Color for Storm Surge Advisory 4 and change color layer in Map
- [x] Collapsible Storm Surge Hazards Components
