### ISSUE TITLE
[Epic] Feature/Noah-Playground(MVP2): Landslide Functionalities

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#69]
### To Do's
- [x] Show/Hide layers for Landslide Hazards Component
- [x] Toggle layers and show to Map for Landslide
- [x] Toggle layers and show to Map for Alluvial Fan
- [x] Toggle layers and show to Map for Unstable Slopes
- [x] Can change Opacity from 0 to 100 for Landslide
- [x] Can change Opacity from 0 to 100 for Alluvial Fan
- [x] Can change Opacity from 0 to 100 for Unstable Slopes
- [x] Can choose Color for Landslide and change color layer in Map
- [ ] Can choose Color for Alluvial Fan and change color layer in Map
- [ ] Can choose Color for Unstable Slopes and change color layer in Map
- [x] Collapsible Landslide Hazards Components
