### ISSUE TITLE
[Epic] Feature/know-your-hazards: Storm Surge Component

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#72]
### To Do's
- [x] Show Risk level results in Side Bar
- [x] Create component for Storm Surge Info
- [x] Change Map Layers into Storm Surge only
