### ISSUE TITLE
[Epic] Feature/know-your-hazards: Landslide Component

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#73]
### To Do's
- [x] Show Risk level results in Side Bar
- [x] Create component for Landslide Info
- [x] Change Map Layers into Landslide only
