### ISSUE TITLE
[Epic] Feature/know-your-hazards: Geolocation

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#75]
### To Do's
- [x] Locate current location of the user
- [x] Zoom in and out in Map
- [x] Icon for geolocation 
- [x] Show Location in My Location in Side Bar
