### ISSUE TITLE
[UI] Feature/know-your-hazards: Component and Routing Modules

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#76]
### To Do's
- [x] Add Hazard and KYH service
- [x] Add store for know-your-hazards
- [x] Generate component for each layer(flood, storm surge, landslide, critical facilities, map, and search)
- [x] Create routing module
