### ISSUE TITLE
[UI] Feature/Noah-Playground(MVP2): Component and Routing Modules

### ISSUE THREAD

**Issue by bon-carpo** [UPRI-NOAH/noah-frontend#77]
### To Do's
- [x] Add noah-playground service
- [x] Add store for noah-playground
- [x] Generate component for each layer(flood, storm surge, landslide, critical facilities, map, and search)
- [x] Create routing module
