### ISSUE TITLE
[UI] Update NOAH Icons to use UN's standard icons

### ISSUE THREAD

**Issue by jadurani** [UPRI-NOAH/noah-frontend#83]
# Tasks

- [ ] Go to https://thenounproject.com/ 
- [ ] Shortlist icons for the following (they must have both PNG and SVG versions)
  - [ ] Hospitals
  - [ ] Fire Stations
  - [ ] Police Stations
  - [ ] Schools
- [ ] Download the icons' PNG versions
- [ ] Download the icons' SVG versions (if any)
  - [ ] You will need to check which ones have downloadable SVG versions. We need the SVG versions to change the color of the icon later on. (This is only a possibility for now, we're not yet sure how we  can change the color a custom icons in mapbox)
- [ ] Research: Can we use an svg image as an icon in mapbox?
  - [ ] Comment your findings in this issue
  - [ ] If yes, then proceed with using the SVG versions and change icons that we use in all areas that we use icons (PHA, Playground, etc)

## Request

- Slack: https://noahdev.slack.com/archives/CGP27BHPV/p1625797844000700

![image](https://user-images.githubusercontent.com/11599005/125067666-22274c00-e0e7-11eb-8a16-c689103bbb2f.png)

## Links
- https://reliefweb.int/report/world/humanitarian-and-country-icons-2018
- https://reliefweb.int/sites/reliefweb.int/files/resources/POSTER_0.pdf
